openapi: 3.0.1
info:
  title: arzt.shopping public API
  description: API for https://arzt.shopping
  version: '0.3'
servers:
  - url: https://europe-west6-cash36-prod-262508.cloudfunctions.net
features.openapi:
  hideTryItPanel: false 
paths:
  /testOrders:
    get:
      description: Get orders of a location
      parameters:
        - name: start_date
          in: query
          schema:
            type: string
            format: date-time
          example: '2023-01-01'
        - name: x-api-key
          in: header
          schema:
            type: string
          example: demo
      responses:
        '200':
          description: Orders from a specific date
      servers:
        - url: https://europe-west6-cash36-prod-262508.cloudfunctions.net

      x-code-samples:
        - lang: shell
          label: cURL
          source: |
            curl -X GET https://api.example.com/users
        - lang: javascript
          label: JavaScript
          source: |
            fetch('https://api.example.com/users')
              .then(response => response.json())
              .then(data => console.log(data))
        - lang: java
          label: Java
          source: |
            OkHttpClient client = new OkHttpClient();
            Request request = new Request.Builder()
              .url("https://api.example.com/users")
              .build();
            Response response = client.newCall(request).execute();
            String responseBody = response.body().string();
