openapi: "3.0.0"
info:
  title: "My API"
  version: "1.0.0"
servers:
  - url: "https://api.example.com"

x-tagGroups:
  - name: "Users"
    tags:
      - "Users"

tags:
  - name: "Users"
    description: "Operations related to users"
    externalDocs:
      description: "Find out more"
      url: "https://example.com"

paths:
  /users:
    get:
      summary: "Get a list of users"
      tags:
        - "Users"
      responses:
        200:
          description: "List of users"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                      format: email
      x-code-samples:
        - lang: php
          label: PHP
          source: |
            <?php
            $ch = curl_init('https://api.example.com/users');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            $response = curl_exec($ch);
            curl_close($ch);
            $users = json_decode($response, true);
            ?>
        - lang: shell
          label: cURL
          source: |
            curl -X GET https://api.example.com/users
        - lang: javascript
          label: JavaScript
          source: |
            fetch('https://api.example.com/users')
              .then(response => response.json())
              .then(data => console.log(data))
        - lang: java
          label: Java
          source: |
            OkHttpClient client = new OkHttpClient();
            Request request = new Request.Builder()
              .url("https://api.example.com/users")
              .build();
            Response response = client.newCall(request).execute();
            String responseBody = response.body().string()

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
