name: Generate OpenAPI Documentation and Exe file

on:
  push:
    branches:
      - main
      - medisync
      
 
jobs:
  build-medsync:
    runs-on: windows-latest
    name: Windows build
    steps:
      - name: Check out repository code for PS1 
        uses: actions/checkout@v3
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ps2exe        
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          ps2exe medsync/medsync.ps1 medsync/medsync.exe    
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Generate Html
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: html2
        config-file: openapi-html-config.yml
        openapi-file: api-spec.yml
        
    - name: Commit and push generated documentation
      run: |
        git config --global user.name "vladae36"
        git add docs
        git commit -m "Generate OpenAPI documentation"
        git push


