name: Generate OpenAPI Documentation

on: push
 
jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Generate Html
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: html2
        config-file: openapi-html-config.yml
        openapi-file: api-spec.yml
        
    - name: Commit and push generated documentation
      run: |
        git config --global user.name "vladae36"
        git add docs
        git commit -m "Generate OpenAPI documentation"
        git push
