name: Generate  Exe file

on: [push]

jobs:
  build-medsync:
    runs-on: windows-latest
    name: Windows build
    steps:
      - name: Check out repository code for PS1 
        uses: actions/checkout@v3
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted       
          Install-Module ps2exe -Scope AllUsers
          Import-Module ps2exe -UseWindowsPowerShell
      - name: generate exe
        shell: pwsh
        run: |
          Invoke-ps2exe medsync/medsync.ps1 medsync/medsync.exe    
 